# docker-compose.dev.yml

services:
  app:
    build:
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./logs:/app/logs
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload